server:
  port: 8080

spring:
  datasource:
    username: dzpt
    password: dzpt
    url: jdbc:mysql://10.2.1.226:3306/dzpt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ourteam.dzpt.entity

web:
  upload-path: upload/

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:logback-boot.xml