server:
  port: 8080

spring:
  datasource:
    username: dzpt
    password: dzpt
    url: jdbc:mysql://localhost/dzpt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ourteam.dzpt.entity

web:
  upload-path: C:/dzpt/upload/
